### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by NouraldinS** [facg3/gaza-works-online#50]
RELATES #1 
As a guest on the website...
I'd like to create a new account easily and understand the process of account creation so that I can use the website's features.

# Acceptance criteria 
- [x] Create signup landing page. #51 
- [x] Create ./public/js/signup.js #53 
- [x] Create signup route. #52 
- [x] Create signup handler. #55 
- [x] Create ./src/libs/signupValidator.js #56 
- [x] Create ./src/libs/bcrypt.js #54 
- [x] Create signup queries (insertUser.js, selectUser) #58
