### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by NouraldinS** [facg3/gaza-works-online#59]
RELATES #1 
As an existing user... 
I expect to have a page that helps me log in and continue using the site so that I can proceed using the website with my previous progress.
# Acceptance Criteria
- [x] Create login landing page #60  
- [x] Create ./public/js/login.js #62 
- [x] Create login route. #61 
- [x] Create login handler. #63 
- [x] Create ./src/libs/jwt.js #64
