### ISSUE TITLE
Post a project

### ISSUE THREAD

**Issue by NouraldinS** [facg3/gaza-works-online#66]
RELATES #1 
As a user...
I expect to be able to post a project to the public for people to find and apply for. My post project is expected to be full and descriptive for a user to understand and apply for, short and easy for me to fill. 

# Acceptance Criteria
- [ ] Create a post project landing page meeting the user's needs. #67
- [ ] Create ./public/js/postProject.js #71
- [ ] Create postProject route. #68
- [ ] Create postProject handler. #70 
- [ ] Create ./src/libs/postProjectValidator.js #73
- [ ] Create query (insertProject). #72
