### ISSUE TITLE
Find a project

### ISSUE THREAD

**Issue by NouraldinS** [facg3/gaza-works-online#74]
RELATES #1 
As a user...
I expect to be able to find projects compatible with my skills to apply for. I should be able navigate through categories and it's sub-categories to select one compatible with my skills.
# Acceptance Criteria
## Categories Landing Page.
- [x] Create categories landing page. #75
- [x] Create categories route. #76
- [x] Create categories handler. #78 
- [x] Create a query (selectAllCats). #80 
-----
## Single Categories Landing Page.
- [x] Create singleCategory landing page. #77
- [x] Create singleCategory route. #79  
- [x] Create singleCategory handler. #81 
- [x] Create a query (selectAllProjects, selectAllSkills). #82
