### ISSUE TITLE
View a project

### ISSUE THREAD

**Issue by NouraldinS** [facg3/gaza-works-online#83]
RELATES #1 
As a user who posted a project...
I expect to view my last project\s more easily and view the project page.
As any user...
I expect to view a project, the project must have a descriptive landing page. I should be able to see how to apply for this project and see comments. 
# Acceptance Criteria
- [x] Create a project landing page. #88 
- [x] Create a project route. #90 
- [x] Create a project handler. #89 
- [x] Create queries (selectProject, selectProposals, selectComments). #92
